name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Railway
      uses: docker/login-action@v2
      with:
        registry: registry.railway.app
        username: ${{ secrets.RAILWAY_TOKEN }}
        password: ${{ secrets.RAILWAY_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.railway.app/katakonsumen:latest

    - name: Deploy to Railway
      uses: railwayapp/cli-action@v1
      with:
        service: kata-konsumen
        token: ${{ secrets.RAILWAY_TOKEN }}
